"""Migración inicial - creación de tablas

Revision ID: addaeee66433
Revises: 
Create Date: 2025-06-15 03:20:17.690569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addaeee66433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('url_pago', sa.String(), nullable=False),
    sa.Column('id_transaccion', sa.String(), nullable=False),
    sa.Column('estado_pago', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=False),
    sa.Column('fecha_finalizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compra')
    op.drop_table('plan')
    # ### end Alembic commands ###
