version: '3'

services:
  app-db:
    image: postgres:13
    container_name: app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app-web:
    container_name: app-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.9
        - DEV_MODE=${DEV_MODE:-false}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@app-db/payments_db
    depends_on:
      - app-db
    volumes:
      - .:/app:cached
    dns:
      - 8.8.8.8
      - 8.8.4.4


volumes:
  postgres_data:
